### Config file for borgsummon

# This is a TOML v0.4.0 document
# See https://github.com/toml-lang/toml/blob/v0.4.0/README.md


# You can import other config files, for example to put configuration
#  for different backup sources in separate files.
include = ['~/.borg-summon/config.d/*', '~/.borg-summon/secrets.toml']

alert_hook = '~/bin/panic.sh'
log_file = '/var/log/borg-summon.log'
ssh_command = 'ssh -i ~/.ssh/id_rsa'
log_level = "warning"
exclude_file = "~/.borg-summon/exclude.txt"
remote_borg_path = "/usr/bin/borg"
progress = true
stats = true

[remotes]
    [remotes.local]
        location = "/path/to/parent/of/repo/"
        umask = "0007"

    [remotes.server]
        location = "borg@server.example.com:/path/to/parent/of/repo"

[backup]
    [backup.init]
        encryption = "repokey"
        append_only = "false"
        
    [backup.create]
        archive_name_template = "auto_{datetime}"
        compression = "lz4"
        exclude_caches = true
        one_file_system = true

    [backup.sources]
        [backup.sources.home]
            paths = ["~", "/etc/"]
            sudo = true
            passphrase = "wowmuchsecret" # Should be kept in separate file with

        [backup.sources.online]
            paths = ["/home/onlinebackup"]
            sudo_user = "onlinebackup"
            backup_remotes = ["local"] # Defaults to all

        [backup.sources.database]
            pre_backup_hook = { command = "dbdump-create.sh", sudo = true, sudo_user = "postgres" }
            paths = ["/tmp/db-backup/dbdump.sql"]
            post_backup_hook = { command = "dbdump-remove.sh" }

        [backup.sources.lvm_example]
            sudo = true
            paths = ["/mnt/snapshot"]
            pre_backup_hook = { command = "create-and-mount-snapshot.sh" }
            post_backup_hook = { command = "unmount-and-remove-snapshot.sh" }
            repo_name = "foo"



[maintain]
    [maintain.prune]
        keep_within = 48
        keep_daily = 14
        keep_weekly = 8
        keep_monthly = 24
        keep_yearly = 100
        prefixes = ["auto"]
        state = true


    [maintain.check]
        repository_only = false
        archives_only = false
        check_last = 0
        # prefixes = []

    [maintain.extract]
        repository_only = false
        archives_only = false
        check_last = 0

    [[maintain.repos]]
        remote = "local"
        repo_name = "home"

    [[maintain.repos]]
        remote = "local"
        repo_name = "database"
        enable_check = false

    [[maintain.repos]]
        remote = "server"
        repo_name = "home"
        enable_prune = false
        enable_extract = false


# Should be placed in an included file, with strict read permissions.
[secret.local.home]
    passphrase = "this_is_a_secret"
[secret.server.home]
    passphrase = "this_is_a_secret"
